### PR TITLE
Add Many-to-Many relationship between Group and Member

### LINKED ISSUE #265: The same member ID cannot be used in more than 1 group
We need to create a Many-to-Many relationship between Group and Member (a Group can contain multiple Members and a Member can join one or more Groups).

### PR DESCRIPTION
**Pull request by 0xjei**
## Description

This PR introduces a Many-to-Many relationship between Group and Member (a Group can contain multiple Members and a Member can join one or more Groups). The relationship is unidirectional and maintained in the Group. This allows for a join table between Group and Member that does not affect the current APIs, introducing an externally imperceptible (non-breaking) change. This approach was chosen because the join table did not require additional information beyond the Group and Member identifiers having a relationship, denoted by the term `Membership`.

## Related Issue
- fix #265 
- complete https://github.com/privacy-scaling-explorations/bandada/pull/267
 
## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

**Comment by 0xjei** [comment]
#305 could be potentially related to this. Need further check

**Comment by 0xjei** [comment]
Are we sure we want to maintain this `Unexpected await inside a loop  no-await-in-loop` lint error?

**Comment by vplasencia** [comment]
> Are we sure we want to maintain this `Unexpected await inside a loop no-await-in-loop` lint error? @vplasencia

Hey! What do you mean? It is better to fix all the errors.

**Comment by 0xjei** [comment]
> > Are we sure we want to maintain this `Unexpected await inside a loop no-await-in-loop` lint error? @vplasencia
> 
> Hey! What do you mean? It is better to fix all the errors.



> > Are we sure we want to maintain this `Unexpected await inside a loop no-await-in-loop` lint error? @vplasencia
> 
> Hey! What do you mean? It is better to fix all the errors.

nvm, everything should be okay with the last commit. Used a `map` with `Promise.all()` instead of a `for` loop.

**Comment by 0xjei** [comment]
> > > Are we sure we want to maintain this `Unexpected await inside a loop no-await-in-loop` lint error? @vplasencia
> > 
> > 
> > Hey! What do you mean? It is better to fix all the errors.
> 
> > > Are we sure we want to maintain this `Unexpected await inside a loop no-await-in-loop` lint error? @vplasencia
> > 
> > 
> > Hey! What do you mean? It is better to fix all the errors.
> 
> nvm, everything should be okay with the last commit. Used a `map` with `Promise.all()` instead of a `for` loop.

@vplasencia Ready for review :)

**Review by vplasencia — APPROVED** [review]

**Pull request merged**
